print ("Exercise N 3,a")
print ("*""\n" "**""\n""***","\n""****")
print ("Exercise N 3,b")
print ("*");"\n";print ("**");"\n";print ("***");"\n";print ("****")
print ("Exercise N 3,c")
print ("*")
print ("**")
print ("***")
print ("****")