first_number = int(input("Enter a number: "))
second_number = int(input("Enter a number: "))
third_number = int(input("Enter a number: "))
total = (first_number + second_number + third_number)
average = ((first_number + second_number + third_number) / 3)
print(total,round(average,2))