print ("Exercise N 2,a")
print ("*******************""\n" "* 		  *""\n""* 		  *","\n""*******************")
print ("Exercise N 2,b")
print ("*******************");"\n";print ("* 		  *");"\n";print ("* 		  *");"\n";print ("*******************")
print ("Exercise N 2,c")
print ("*******************")
print ("*                 *")
print ("*                 *")
print ("*******************")