#!usr/bin/evn python3

print(1, "\t", oct(1), "\t", hex(1).capitalize(), "\t", bin(1))
print(2, "\t", oct(2), "\t", hex(2).capitalize(), "\t", bin(2))
print(3, "\t", oct(3), "\t", hex(3).capitalize(), "\t", bin(3))
print(4, "\t", oct(4), "\t", hex(4).capitalize(), "\t", bin(4))
print(5, "\t", oct(5), "\t", hex(5).capitalize(), "\t", bin(5))
print(6, "\t", oct(6), "\t", hex(6).capitalize(), "\t", bin(6))
print(7, "\t", oct(7), "\t", hex(7).capitalize(), "\t", bin(7))
print(8, "\t", oct(8), "\t", hex(8).capitalize(), "\t", bin(8))
print(9, "\t", oct(9), "\t", hex(9).capitalize(), "\t", bin(9))
print(10, "\t", oct(10), "\t", hex(10).capitalize(), "\t", bin(10))
print(11, "\t", oct(11), "\t", hex(11).capitalize(), "\t", bin(11))
print(12, "\t", oct(12), "\t", hex(12).capitalize(), "\t", bin(12))
print(13, "\t", oct(13), "\t", hex(13).capitalize(), "\t", bin(13))
print(14, "\t", oct(14), "\t", hex(14).capitalize(), "\t", bin(14))
print(15, "\t", oct(15), "\t", hex(15).capitalize(), "\t", bin(15))
print(16, "\t", oct(16), "\t", hex(16).capitalize(), "\t", bin(16))
print(17, "\t", oct(17), "\t", hex(17).capitalize(), "\t", bin(17))