#!usr/bin/evn python3
decimal = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
octal = (oct(number) for number in decimal)
hexadecimal = (hex(number) for number in decimal)
binary = (bin(number) for number in decimal)
print(oct(decimal))


print(decimal[0], "\t", octal[0], "\t", hexadecimal[0], "\t", binary[0])
print(decimal[1], "\t", octal[1], "\t", hexadecimal[1], "\t", binary[1])
print(decimal[2], "\t", octal[2], "\t", hexadecimal[2], "\t", binary[2])
print(decimal[3], "\t", octal[3], "\t", hexadecimal[3], "\t", binary[3])
print(decimal[4], "\t", octal[4], "\t", hexadecimal[4], "\t", binary[4])
print(decimal[5], "\t", octal[5], "\t", hexadecimal[5], "\t", binary[5])
print(decimal[6], "\t", octal[6], "\t", hexadecimal[6], "\t", binary[1])
print(decimal[7], "\t", octal[7], "\t", hexadecimal[7], "\t", binary[1])
print(decimal[8], "\t", octal[8], "\t", hexadecimal[8], "\t", binary[1])
print(decimal[9], "\t", octal[9], "\t", hexadecimal[9], "\t", binary[1])
print(decimal[10], "\t", octal[10], "\t", hexadecimal[10], "\t", binary[10])
print(decimal[11], "\t", octal[11], "\t", hexadecimal[11], "\t", binary[11])
print(decimal[12], "\t", octal[12], "\t", hexadecimal[12], "\t", binary[12])
print(decimal[13], "\t", octal[13], "\t", hexadecimal[13], "\t", binary[13])
print(decimal[14], "\t", octal[14], "\t", hexadecimal[14], "\t", binary[14])
print(decimal[15], "\t", octal[15], "\t", hexadecimal[15], "\t", binary[15])
print(decimal[16], "\t", octal[16], "\t", hexadecimal[16], "\t", binary[16])
print(decimal[17], "\t", octal[17], "\t", hexadecimal[17], "\t", binary[17])